version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_tele
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - EXECUTIONS_PROCESS=main
      - N8N_LOG_LEVEL=info
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - n8n-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n_data:
    driver: local

networks:
  n8n-network:
    driver: bridge
